name: Docker

on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v1
#        with:
#          platforms: all

      - name: Login
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: xyz # ${{ secrets.GITHUB_TOKEN }}        

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64 #,linux/arm64
          push: true
          tags: "docker.pkg.github.com/${{ github.repository }}/azcopy:${{ github.run_number }},docker.pkg.github.com/${{ github.repository }}/azcopy:latest"
